sonar.projectKey=Skylar3017_UCV_ATE_SI_LAB011
sonar.organization=skylar3017

# Nombre del proyecto en SonarCloud
sonar.projectName=UCV Alpha Beta Lab

# Carpetas del proyecto
sonar.sources=src
sonar.tests=tests

# Reporte de cobertura generado por pytest
sonar.python.coverage.reportPaths=coverage.xml

# Codificación
sonar.sourceEncoding=UTF-8